version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mowthos:mowthos@db:5432/mowthos_cluster
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - DEBUG=True
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mowthos_cluster
      - POSTGRES_USER=mowthos
      - POSTGRES_PASSWORD=mowthos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 